import { Question } from '../../../types';

export const level2Questions: Question[] = [
  {
    id: "ex_ed_u4_l6_lv2_1-2026",
    question: "What is the active electrophile in the nitration of benzene, and how is it generated using concentrated nitric and sulfuric acids?",
    options: [
      { text: "NO₂⁺ (nitronium ion), generated by: HNO₃ + 2H₂SO₄ ⇌ NO₂⁺ + 2HSO₄⁻ + H₃O⁺", isCorrect: true },
      { text: "NO₂⁻ (nitrite ion), generated by dissociation of nitric acid" },
      { text: "NO⁺ (nitrosonium ion), generated by thermal decomposition of HNO₃" },
      { text: "NO₃⁻ (nitrate ion), acting as an oxidising agent" }
    ],
    correctAnswer: 0,
    explanation: "* In the nitrating mixture, concentrated $\\\\text{H}_2\\\\text{SO}_4$ acts as a stronger acid than $\\\\text{HNO}_3$, protonating it.\n* The protonated intermediate loses water to generate the powerful electrophile $\\\\text{NO}_2^+$ (the nitronium ion).",
    level: 2,
    topic: "edexcel-unit-4",
    lessonNum: 6,
    curriculum: "edexcel-alevel",
    paperType: "mcq",
    source: "Pearson Edexcel IAL Chemistry WCH14/01 / Oct 2025 Paper 1 Q75",
    createdAt: "2026-09-01T10:00:00Z"
  },
  {
    id: "ex_ed_u4_l6_lv2_2-2026",
    question: "Why is an anhydrous halogen carrier such as AlCl₃ or FeBr₃ required when reacting benzene with halogens?",
    options: [
      { text: "Benzene's π-electron density is insufficient to polarise a halogen molecule without a Lewis acid catalyst", isCorrect: true },
      { text: "The halogen carrier reduces benzene into cyclohexane first" },
      { text: "It prevents substitution and forces an addition reaction" },
      { text: "It acts as a Brønsted–Lowry base to accept protons from benzene" }
    ],
    correctAnswer: 0,
    explanation: "* Unlike alkenes, the delocalised $\\\\pi$-electrons in benzene are too stable to polarise non-polar halogen molecules (e.g. $\\\\text{Br}_2$).\n* The halogen carrier is an electron-deficient Lewis acid that accepts an electron pair from the halogen, generating a potent electrophile (e.g. $\\\\text{Br}^+$).",
    level: 2,
    topic: "edexcel-unit-4",
    lessonNum: 6,
    curriculum: "edexcel-alevel",
    paperType: "mcq",
    source: "Pearson Edexcel IAL Chemistry WCH14/01 / June 2026 Paper 1 Q76",
    createdAt: "2026-09-01T10:00:00Z"
  },
  {
    id: "ex_ed_u4_l6_lv2_3-2026",
    question: "Which reagents and catalyst are needed to carry out Friedel–Crafts acylation of benzene to prepare phenylethanone (acetophenone)?",
    options: [
      { text: "CH₃COCl and anhydrous AlCl₃", isCorrect: true },
      { text: "CH₃CH₂Cl and concentrated H₂SO₄" },
      { text: "CH₃COOH and concentrated HCl" },
      { text: "CH₃CHO and nickel catalyst" }
    ],
    correctAnswer: 0,
    explanation: "* Friedel–Crafts acylation requires an acyl chloride (ethanoyl chloride, $\\\\text{CH}_3\\\\text{COCl}$) and a halogen carrier catalyst ($\\\\text{AlCl}_3$).\n* The reaction forms the acylium ion $\\\\text{CH}_3\\\\text{C}^+=\\\\text{O}$, which attacks the benzene ring to yield phenylethanone.",
    level: 2,
    topic: "edexcel-unit-4",
    lessonNum: 6,
    curriculum: "edexcel-alevel",
    paperType: "mcq",
    source: "Pearson Edexcel IAL Chemistry WCH14/01 / Jan 2026 Paper 1 Q65",
    createdAt: "2026-09-01T10:00:00Z"
  },
  {
    id: "ex_ed_u4_l6_lv2_4-2026",
    question: "Which of the following correctly ranks the substances in order of INCREASING basicity (weakest base to strongest base)?",
    options: [
      { text: "Phenylamine < Ammonia < Ethylamine", isCorrect: true },
      { text: "Ethylamine < Ammonia < Phenylamine" },
      { text: "Ammonia < Phenylamine < Ethylamine" },
      { text: "Ethylamine < Phenylamine < Ammonia" }
    ],
    correctAnswer: 0,
    explanation: "* In phenylamine, the nitrogen lone pair delocalises into the benzene $\\\\pi$-system, making it least available to accept a proton (weakest base).\n* In ethylamine, the electron-donating alkyl group increases electron density on the nitrogen, making the lone pair most available (strongest base).",
    level: 2,
    topic: "edexcel-unit-4",
    lessonNum: 6,
    curriculum: "edexcel-alevel",
    paperType: "mcq",
    source: "Pearson Edexcel IAL Chemistry WCH14/01 / Oct 2025 Paper 1 Q76",
    createdAt: "2026-09-01T10:00:00Z"
  },
  {
    id: "ex_ed_u4_l6_lv2_5-2026",
    question: "What reagents and conditions are used in the industrial or laboratory reduction of nitrobenzene to produce phenylamine?",
    options: [
      { text: "Tin (Sn) and concentrated hydrochloric acid, heated under reflux, followed by excess NaOH(aq)", isCorrect: true },
      { text: "NaBH₄ in aqueous methanol at room temperature" },
      { text: "Acidified potassium manganate(VII) heated under reflux" },
      { text: "Chlorine gas in the presence of UV light" }
    ],
    correctAnswer: 0,
    explanation: "* Nitrobenzene is reduced by heating under reflux with tin ($\\\\text{Sn}$) and concentrated $\\\\text{HCl}$, forming the phenylammonium ion (C₆H₅NH₃⁺).\n* Adding excess aqueous $\\\\text{NaOH}$ liberates free phenylamine (C₆H₅NH₂).",
    level: 2,
    topic: "edexcel-unit-4",
    lessonNum: 6,
    curriculum: "edexcel-alevel",
    paperType: "mcq",
    source: "Pearson Edexcel IAL Chemistry WCH14/01 / June 2025 Paper 1 Q77",
    createdAt: "2026-09-01T10:00:00Z"
  },
  {
    id: "ex_ed_u4_l6_lv2_6-2026",
    question: "Why is the nucleophilic substitution reaction between 1-bromoethane and excess concentrated ethanolic ammonia preferred over an equimolar mixture for preparing ethylamine?",
    options: [
      { text: "Excess ammonia minimises multiple alkylation by competing effectively with primary amine products", isCorrect: true },
      { text: "Equimolar ammonia completely suppresses the formation of ethylamine" },
      { text: "Excess ammonia acts as a halogen carrier catalyst" },
      { text: "Excess ammonia oxidises any formed secondary amines" }
    ],
    correctAnswer: 0,
    explanation: "* The primary amine product (ethylamine) is a nucleophile and can react further with 1-bromoethane to form secondary and tertiary amines.\n* Using excess ammonia ensures that 1-bromoethane is overwhelmingly likely to collide with ammonia molecules rather than ethylamine, maximising the yield of primary amine.",
    level: 2,
    topic: "edexcel-unit-4",
    lessonNum: 6,
    curriculum: "edexcel-alevel",
    paperType: "mcq",
    source: "Pearson Edexcel IAL Chemistry WCH14/01 / Jan 2026 Paper 1 Q66",
    createdAt: "2026-09-01T10:00:00Z"
  },
  {
    id: "ex_ed_u4_l6_lv2_7-2026",
    question: "What is the organic product formed when ethanoyl chloride (CH₃COCl) reacts vigorously at room temperature with ethylamine (CH₃CH₂NH₂)?",
    options: [
      { text: "N-ethylethanamide", isCorrect: true },
      { text: "Aminoethane hydrochloride" },
      { text: "Diethylamine" },
      { text: "Ethanoic anhydride" }
    ],
    correctAnswer: 0,
    explanation: "* The nucleophilic addition-elimination reaction between an acyl chloride and a primary amine forms a secondary amide.\n* $\\\\text{CH}_3\\\\text{COCl} + 2\\\\text{CH}_3\\\\text{CH}_2\\\\text{NH}_2 \\\\rightarrow \\\\text{CH}_3\\\\text{CONHCH}_2\\\\text{CH}_3 + \\\\text{CH}_3\\\\text{CH}_2\\\\text{NH}_3^+\\\\text{Cl}^-$, producing N-ethylethanamide.",
    level: 2,
    topic: "edexcel-unit-4",
    lessonNum: 6,
    curriculum: "edexcel-alevel",
    paperType: "mcq",
    source: "Pearson Edexcel IAL Chemistry WCH14/01 / Oct 2025 Paper 1 Q77",
    createdAt: "2026-09-01T10:00:00Z"
  },
  {
    id: "ex_ed_u4_l6_lv2_8-2026",
    question: "When an amino acid such as alanine is placed in a solution of low pH (strongly acidic conditions), what is the predominant ionic form?",
    options: [
      { text: "CH₃–CH(NH₃⁺)–COOH (cationic form)", isCorrect: true },
      { text: "CH₃–CH(NH₂)–COO⁻ (anionic form)" },
      { text: "CH₃–CH(NH₃⁺)–COO⁻ (zwitterion form)" },
      { text: "CH₃–CH(NH₂)–COOH (uncharged molecule)" }
    ],
    correctAnswer: 0,
    explanation: "* In strongly acidic conditions (excess $\\\\text{H}^+$), the carboxylate group of the zwitterion is protonated ($-\\\\text{COO}^- + \\\\text{H}^+ \\\\rightarrow -\\\\text{COOH}$).\n* The amino group remains protonated as $-\\\\text{NH}_3^+$, giving an overall positive charge ($+1$ cation).",
    level: 2,
    topic: "edexcel-unit-4",
    lessonNum: 6,
    curriculum: "edexcel-alevel",
    paperType: "mcq",
    source: "Pearson Edexcel IAL Chemistry WCH14/01 / June 2026 Paper 1 Q78",
    createdAt: "2026-09-01T10:00:00Z"
  },
  {
    id: "ex_ed_u4_l6_lv2_9-2026",
    question: "What is meant by the isoelectric point (pI) of an amino acid?",
    options: [
      { text: "The pH at which the amino acid has no net electrical charge and exists predominantly as a zwitterion", isCorrect: true },
      { text: "The temperature at which an amino acid decomposes" },
      { text: "The pH at which the amino acid is completely un-ionised" },
      { text: "The voltage required to separate the amino acid during gel electrophoresis" }
    ],
    correctAnswer: 0,
    explanation: "* The isoelectric point (pI) is the specific pH at which the mean net electric charge of the amino acid is zero.\n* At this pH, the zwitterionic form dominates, and the molecule will not migrate towards either electrode in an electric field.",
    level: 2,
    topic: "edexcel-unit-4",
    lessonNum: 6,
    curriculum: "edexcel-alevel",
    paperType: "mcq",
    source: "Pearson Edexcel IAL Chemistry WCH14/01 / Jan 2026 Paper 1 Q67",
    createdAt: "2026-09-01T10:00:00Z"
  },
  {
    id: "ex_ed_u4_l6_lv2_10-2026",
    question: "Which of the following monomers can undergo condensation polymerisation to produce a polyamide (such as Nylon-6,6)?",
    options: [
      { text: "1,6-diaminohexane and hexanedioic acid", isCorrect: true },
      { text: "Ethane-1,2-diol and benzene-1,4-dicarboxylic acid" },
      { text: "Ethene and propene" },
      { text: "Phenol and methanal" }
    ],
    correctAnswer: 0,
    explanation: "* Nylon-6,6 is a synthetic polyamide made from a 6-carbon diamine (1,6-diaminohexane) and a 6-carbon dicarboxylic acid (hexanedioic acid).\n* Eliminating water between amine and carboxyl groups forms recurring amide links ($-\\\\text{CONH}-$).",
    level: 2,
    topic: "edexcel-unit-4",
    lessonNum: 6,
    curriculum: "edexcel-alevel",
    paperType: "mcq",
    source: "Pearson Edexcel IAL Chemistry WCH14/01 / Oct 2025 Paper 1 Q78",
    createdAt: "2026-09-01T10:00:00Z"
  },
  {
    id: "ex_ed_u4_l6_lv2_11-2026",
    question: "What reagents and conditions are required to hydrolyse a polyamide into its constituent diamine and dicarboxylic acid?",
    options: [
      { text: "Heating under prolonged reflux with moderately concentrated aqueous strong acid (e.g. 6 mol dm⁻³ HCl)", isCorrect: true },
      { text: "Shaking with cold dilute sodium hydroxide" },
      { text: "Passing dry chlorine gas over the molten polymer" },
      { text: "Heating with hydrogen gas and a platinum catalyst" }
    ],
    correctAnswer: 0,
    explanation: "* Polyamides are hydrolysed by heating under reflux with concentrated acid (such as $6\\\\text{ mol dm}^{-3}\\\\text{ HCl}$).\n* Acid hydrolysis breaks the amide bonds to yield the dicarboxylic acid and the protonated diammonium salt.",
    level: 2,
    topic: "edexcel-unit-4",
    lessonNum: 6,
    curriculum: "edexcel-alevel",
    paperType: "mcq",
    source: "Pearson Edexcel IAL Chemistry WCH14/01 / June 2025 Paper 1 Q79",
    createdAt: "2026-09-01T10:00:00Z"
  },
  {
    id: "ex_ed_u4_l6_lv2_12-2026",
    question: "Why does phenol react much more rapidly with bromine water than benzene does (producing a white precipitate without needing a halogen carrier)?",
    options: [
      { text: "A lone pair on the oxygen atom delocalises into the benzene π-system, increasing electron density and activating the ring", isCorrect: true },
      { text: "The hydroxyl group acts as an electrophile towards bromine" },
      { text: "Phenol is an ionic salt in aqueous solution" },
      { text: "The C–O bond breaks to allow free-radical substitution" }
    ],
    correctAnswer: 0,
    explanation: "* In phenol, one of the lone pairs on the oxygen atom overlaps with the $\\\\pi$-electrons of the benzene ring.\n* This increases the ring's electron density, polarising $\\\\text{Br}_2$ molecules without needing an $\\\\text{FeBr}_3$ catalyst, yielding 2,4,6-tribromophenol rapidly.",
    level: 2,
    topic: "edexcel-unit-4",
    lessonNum: 6,
    curriculum: "edexcel-alevel",
    paperType: "mcq",
    source: "Pearson Edexcel IAL Chemistry WCH14/01 / Jan 2026 Paper 1 Q68",
    createdAt: "2026-09-01T10:00:00Z"
  }
];
