import { LessonPart } from '../../../registry';

export const lessonTitle = "Organic Chemistry: Arenes, Amines, Amides and Amino Acids";
export const lessonNumber = 6;

export const theoryMarkdown = `
# Topic 16: Organic Chemistry: Arenes, Amines, Amides and Amino Acids
This lesson covers the chemistry of benzene and its derivatives (arenes), organic nitrogen compounds including primary/secondary amines, amides, amino acids, and polymerisation (polyesters and polyamides).
`;

export const parts: LessonPart[] = [
    {
        id: 'benzene-structure-reactions-u4-l6',
        title: 'Benzene Structure & Reactions',
        type: 'text',
        content: `
> [!NOTE]
> ### 🛞 The Structure of Benzene
> Benzene ($\\\\text{C}_6\\\\text{H}_6$) has a planar hexagonal ring structure.
> * **Kekulé Structure:** Proposed alternating single and double bonds, which was disproven by:
>   1. **Bond Lengths:** All carbon-carbon bonds in benzene are equal ($0.140\\\\text{ nm}$), which is intermediate between single ($0.154\\\\text{ nm}$) and double ($0.134\\\\text{ nm}$) bonds.
>   2. **Enthalpy of Hydrogenation:** The experimental enthalpy of hydrogenation of benzene is $-208\\\\text{ kJ mol}^{-1}$, which is $152\\\\text{ kJ mol}^{-1}$ more stable than the predicted value for cyclohexa-1,3,5-triene ($-360\\\\text{ kJ mol}^{-1}$). This difference is the **delocalisation (resonance) energy**.
>   3. **Resistance to Bromination:** Benzene does not readily decolourise bromine water, unlike alkenes, showing it does not contain true double bonds.

> [!IMPORTANT]
> ### ⚛️ Delocalised $\\\\pi$-System
> Each carbon in benzene is $\\\\text{sp}^2$ hybridised, bonded to two carbons and one hydrogen.
> * The remaining $p$-orbital on each of the six carbon atoms overlaps sideways above and below the plane of the ring.
> * This forms a delocalised ring of $\\\\pi$-electrons, giving benzene its high thermodynamic stability.

> [!IMPORTANT]
> ### 🧪 Electrophilic Substitution Reactions
> Because of its high electron density, benzene reacts with electrophiles. It undergoes **substitution** rather than addition to preserve the stable delocalised ring.
> 
> 1. **Nitration:**
>    * **Reagents:** Concentrated $\\\\text{HNO}_3$ and concentrated $\\\\text{H}_2\\\\text{SO}_4$ (catalyst).
>    * **Temperature:** $50^\\\\circ\\\\text{C}$ (to prevent multi-substitution).
>    * **Electrophile Generation:** $\\\\text{HNO}_3 + 2\\\\text{H}_2\\\\text{SO}_4 \\\\rightarrow \\\\text{NO}_2^+ + \\\\text{H}_3\\\\text{O}^+ + 2\\\\text{HSO}_4^-$
>    * **Electrophile:** $\\\\text{NO}_2^+$ (nitronium ion).
> 
> 2. **Halogenation:**
>    * **Reagents:** $\\\\text{Cl}_2$ or $\\\\text{Br}_2$ in the presence of a halogen carrier catalyst ($\\\\text{AlCl}_3$, $\\\\text{FeCl}_3$, or $\\\\text{FeBr}_3$).
>    * **Electrophile Generation:** $\\\\text{Br}_2 + \\\\text{FeBr}_3 \\\\rightarrow \\\\text{Br}^+ + \\\\text{FeBr}_4^-$

> [!EXAMPLE]
> #### 📝 Worked Example 1: Nitration Mechanism
> **Question:** Describe the mechanism for the nitration of benzene to form nitrobenzene
> 
> > [!TIP]
> > **🔑 Step-by-step Solution:**
> > 
> > 1. **Generation of the electrophile:**
> >    $$\\\\text{HNO}_3 + 2\\\\text{H}_2\\\\text{SO}_4 \\\\rightarrow \\\\text{NO}_2^+ + \\\\text{H}_3\\\\text{O}^+ + 2\\\\text{HSO}_4^-$$
> > 
> > 2. **Electrophilic Attack:**
> >    * Two electrons from the delocalised $\\\\pi$-system of benzene attack the $\\\\text{NO}_2^+$ ion.
> >    * This breaks the delocalised system, forming a positively charged intermediate with a broken ring (horseshoe shape open towards the attacked carbon).
> > 
> > 3. **Elimination of proton to restore aromaticity:**
> >    * The $\\\\text{C-H}$ bond on the attacked carbon breaks, donating its electrons back to restore the delocalised ring system.
> >    * The $\\\\text{H}^+$ ion released reacts with $\\\\text{HSO}_4^-$ to regenerate the sulfuric acid catalyst:
> >      $$\\\\text{H}^+ + \\\\text{HSO}_4^- \\\\rightarrow \\\\text{H}_2\\\\text{SO}_4$$
`,
        keyPoints: [
            'Benzene undergoes electrophilic substitution, not electrophilic addition, because addition would destroy the stable aromatic system.',
            'The nitronium ion (NO₂⁺) is the active electrophile generated by the reaction between concentrated nitric and sulfuric acids.'
        ]
    },
    {
        id: 'amines-amides-basicity-u4-l6',
        title: 'Amines, Amides & Basicity',
        type: 'text',
        content: `
> [!NOTE]
> ### 🧪 Amines and Amides
> * **Amines:** Derivatives of ammonia where one or more hydrogen atoms are replaced by alkyl or aryl groups ($\\\\text{R-NH}_2$).
> * **Amides:** Contain a carbonyl group directly bonded to a nitrogen atom ($\\\\text{R-CONH}_2$).

> [!IMPORTANT]
> ### 🧮 Basicity of Amines
> Amines act as **weak bases** because the nitrogen atom has a **lone pair of electrons** that can accept a proton ($\\\\text{H}^+$) via a dative covalent bond:
> $$\\\\text{R-NH}_2 + \\\\text{H}^+ \\\\rightarrow \\\\text{R-NH}_3^+$$
> 
> **Order of Basicity:**
> $$\\\\text{Ethylamine} > \\\\text{Ammonia} > \\\\text{Phenylamine}$$
> 
> * **Ethylamine (Alkylamine) is stronger than Ammonia:**
>   * The alkyl group (ethyl) is electron-releasing due to the **inductive effect**. This increases the electron density on the nitrogen atom, making its lone pair more available to accept a proton.
> * **Phenylamine (Arylamine) is weaker than Ammonia:**
>   * The lone pair of electrons on the nitrogen atom overlaps with and becomes **delocalised** into the benzene ring $\\\\pi$-system. This reduces the electron density on the nitrogen, making the lone pair much less available to accept a proton.

> [!EXAMPLE]
> #### 📝 Worked Example 1: Comparing Basicity
> **Question:** Explain why phenylamine is a weaker base than ethylamine
> 
> > [!TIP]
> > **🔑 Step-by-step Solution:**
> > 
> > 1. **Define basicity:** Basicity depends on the availability of the nitrogen lone pair to accept a proton.
> > 
> > 2. **Analyze ethylamine:**
> >    * The ethyl group is electron-donating (+I inductive effect).
> >    * This increases the electron density on the nitrogen, making the lone pair more available.
> > 
> > 3. **Analyze phenylamine:**
> >    * The nitrogen lone pair delocalises into the benzene ring $\\\\pi$-electron system.
> >    * This significantly decreases the electron density on the nitrogen, making the lone pair less available to bind to a proton.
> > 
> > 4. **Conclusion:** Phenylamine is therefore a weaker base than ethylamine.
`,
        keyPoints: [
            'Alkyl groups are electron-donating and increase amine basicity; aryl groups (benzene rings) are electron-withdrawing and decrease it.',
            'Amides are not basic because the lone pair on the nitrogen is delocalised into the adjacent carbonyl group.'
        ]
    },
    {
        id: 'amino-acids-zwitterions-u4-l6',
        title: 'Amino Acids & Zwitterions',
        type: 'text',
        content: `
> [!NOTE]
> ### 🧬 Structure of Amino Acids
> 2-amino acids contain both an amine group ($-\\\\text{NH}_2$) and a carboxylic acid group ($-\\\\text{COOH}$) attached to the same carbon atom.
> * General Formula: $\\\\text{R-CH(NH}_2\\\\text{)COOH}$
> * Except for glycine ($\\\\text{R} = \\\\text{H}$), all 2-amino acids contain a chiral carbon and exhibit optical activity.

> [!IMPORTANT]
> ### 🧮 Zwitterion Formation
> In solid form and in aqueous solutions at their **isoelectric point** (neutral pH), amino acids exist as **zwitterions** (dipolar ions).
> * The acidic $-\\\\text{COOH}$ group donates a proton to the basic $-\\\\text{NH}_2$ group within the same molecule:
>   $$\\\\text{R-CH(NH}_2\\\\text{)COOH} \\\\rightarrow \\\\text{R-CH(NH}_3^+\\\\text{)COO}^-$$
> * **High Melting Points:** Solid amino acids exist as ionic zwitterionic lattices held by strong electrostatic forces, giving them exceptionally high melting points.

> [!TIP]
> ### 🧪 Effect of pH on Amino Acid Structure
> 1. **In Acidic Conditions (low pH):** The zwitterion accepts a proton on the carboxylate group, forming a cation:
>    $$\\\\text{R-CH(NH}_3^+\\\\text{)COOH}$$
> 2. **In Alkaline Conditions (high pH):** The zwitterion donates a proton from the ammonium group, forming an anion:
>    $$\\\\text{R-CH(NH}_2\\\\text{)COO}^-$$

> [!EXAMPLE]
> #### 📝 Worked Example 1: Amino Acid structures at different pH
> **Question:** Draw the structure of alanine ($\\\\text{R} = \\\\text{CH}_3$) at pH 1 and pH 12
> 
> > [!TIP]
> > **🔑 Step-by-step Solution:**
> > 
> > 1. **Identify the zwitterion form of alanine:**
> >    $$\\\\text{CH}_3 - \\\\text{CH(NH}_3^+\\\\text{)COO}^-$$
> > 
> > 2. **Determine structure in acid (pH 1):**
> >    * Excess $\\\\text{H}^+$ protonates the carboxylate group:
> >      $$\\\\text{CH}_3 - \\\\text{CH(NH}_3^+\\\\text{)COOH}$$
> > 
> > 3. **Determine structure in alkali (pH 12):**
> >    * Excess $\\\\text{OH}^-$ removes a proton from the ammonium group:
> >      $$\\\\text{CH}_3 - \\\\text{CH(NH}_2\\\\text{)COO}^-$$
`,
        keyPoints: [
            'All natural amino acids (except glycine) are chiral and exist as single enantiomers.',
            'The isoelectric point is the pH at which an amino acid has no net electrical charge (exists as a zwitterion).'
        ]
    },
    {
        id: 'condensation-polymerisation-u4-l6',
        title: 'Condensation Polymerisation',
        type: 'text',
        content: `
> [!NOTE]
> ### 🧵 Condensation Polymers
> Unlike addition polymerisation, **condensation polymerisation** involves the reaction of monomers with two functional groups, releasing a small molecule (usually $\\\\text{H}_2\\\\text{O}$ or $\\\\text{HCl}$) as a byproduct.
> 
> 1. **Polyesters:** Formed between a dicarboxylic acid and a diol (or a monomer containing both $-\\\\text{COOH}$ and $-\\\\text{OH}$ groups).
>    * Linkage: Ester linkage ($-\\\\text{COO}-$)
>    * Example: Terylene (PET)
> 2. **Polyamides:** Formed between a dicarboxylic acid and a diamine (or an amino acid).
>    * Linkage: Amide / peptide linkage ($-\\\\text{CONH}-$)
>    * Examples: Nylon-6,6 and Kevlar

> [!IMPORTANT]
> ### 🧮 Hydrolysis of Polymers
> Condensation polymers can be broken down back into their monomers by hydrolysis (reacting with water). This makes them **biodegradable** (unlike polyalkenes).
> * **Acid Hydrolysis:** Cleaves amide and ester bonds. Polyamides produce dicarboxylic acids and diammonium salts.
> * **Base Hydrolysis:** Polyesters are easily hydrolysed by hot aqueous $\\\\text{NaOH}$ to yield dicarboxylate salts and diols.

> [!EXAMPLE]
> #### 📝 Worked Example 1: Identifying Monomers
> **Question:** Draw the structures of the monomers used to make the following polyamide section:
> "$$-\text{HN}-\text{CH}_2-\text{NH}-\text{CO}-\text{CH}_2\text{CH}_2-\text{CO}-$$"
> 
> > [!TIP]
> > **🔑 Step-by-step Solution:**
> > 
> > 1. **Locate the amide linkage:**
> >    * Find the bond between the carbonyl carbon ($\\\\text{C}=\\\\text{O}$) and nitrogen ($\\\\text{N-H}$).
> > 
> > 2. **Cleave the bond:**
> >    * Break the $-\\\\text{HN-CO}-$ bond to separate the diamine part and the dicarboxylic acid part.
> > 
> > 3. **Reconstruct the monomers:**
> >    * Add $-\\\\text{H}$ to the nitrogen atoms to restore the amine groups:
> >      $$\\\\text{H}_2\\\\text{N} - \\\\text{CH}_2 - \\\\text{NH}_2\\\\text{ (methanediamine)}$$
> >    * Add $-\\\\text{OH}$ to the carbonyl groups to restore the carboxylic acid groups:
> >      $$\\\\text{HOOC} - \\\\text{CH}_2\\\\text{CH}_2 - \\\\text{COOH\\\\ (butanedioic acid)}$$
`,
        keyPoints: [
            'Condensation polymers are biodegradable because the ester and amide linkages can be hydrolysed, unlike carbon-carbon bonds in addition polymers.',
            'Nylon-6,6 is named because both the diamine and dicarboxylic acid monomers contain six carbon atoms.'
        ]
    }
];
