export interface Element {
    x: number;
    y: number;
    number: number;
    symbol: string;
    name: string;
    mass: string;
    category: string;
}

export const elements: Element[] = [
    // Row 1
    { x: 0, y: 0, number: 1, symbol: 'H', name: 'Hydrogen', mass: '1.008', category: 'nonmetal' },
    { x: 17, y: 0, number: 2, symbol: 'He', name: 'Helium', mass: '4.003', category: 'noble-gas' },
    // Row 2
    { x: 0, y: 1, number: 3, symbol: 'Li', name: 'Lithium', mass: '6.941', category: 'alkali-metal' },
    { x: 1, y: 1, number: 4, symbol: 'Be', name: 'Beryllium', mass: '9.012', category: 'alkaline-earth' },
    { x: 12, y: 1, number: 5, symbol: 'B', name: 'Boron', mass: '10.81', category: 'metalloid' },
    { x: 13, y: 1, number: 6, symbol: 'C', name: 'Carbon', mass: '12.01', category: 'nonmetal' },
    { x: 14, y: 1, number: 7, symbol: 'N', name: 'Nitrogen', mass: '14.01', category: 'nonmetal' },
    { x: 15, y: 1, number: 8, symbol: 'O', name: 'Oxygen', mass: '16.00', category: 'nonmetal' },
    { x: 16, y: 1, number: 9, symbol: 'F', name: 'Fluorine', mass: '19.00', category: 'halogen' },
    { x: 17, y: 1, number: 10, symbol: 'Ne', name: 'Neon', mass: '20.18', category: 'noble-gas' },
    // Row 3
    { x: 0, y: 2, number: 11, symbol: 'Na', name: 'Sodium', mass: '22.99', category: 'alkali-metal' },
    { x: 1, y: 2, number: 12, symbol: 'Mg', name: 'Magnesium', mass: '24.31', category: 'alkaline-earth' },
    { x: 12, y: 2, number: 13, symbol: 'Al', name: 'Aluminum', mass: '26.98', category: 'post-transition' },
    { x: 13, y: 2, number: 14, symbol: 'Si', name: 'Silicon', mass: '28.09', category: 'metalloid' },
    { x: 14, y: 2, number: 15, symbol: 'P', name: 'Phosphorus', mass: '30.97', category: 'nonmetal' },
    { x: 15, y: 2, number: 16, symbol: 'S', name: 'Sulfur', mass: '32.07', category: 'nonmetal' },
    { x: 16, y: 2, number: 17, symbol: 'Cl', name: 'Chlorine', mass: '35.45', category: 'halogen' },
    { x: 17, y: 2, number: 18, symbol: 'Ar', name: 'Argon', mass: '39.95', category: 'noble-gas' },
    // Row 4
    { x: 0, y: 3, number: 19, symbol: 'K', name: 'Potassium', mass: '39.10', category: 'alkali-metal' },
    { x: 1, y: 3, number: 20, symbol: 'Ca', name: 'Calcium', mass: '40.08', category: 'alkaline-earth' },
    { x: 2, y: 3, number: 21, symbol: 'Sc', name: 'Scandium', mass: '44.96', category: 'transition' },
    { x: 3, y: 3, number: 22, symbol: 'Ti', name: 'Titanium', mass: '47.87', category: 'transition' },
    { x: 4, y: 3, number: 23, symbol: 'V', name: 'Vanadium', mass: '50.94', category: 'transition' },
    { x: 5, y: 3, number: 24, symbol: 'Cr', name: 'Chromium', mass: '52.00', category: 'transition' },
    { x: 6, y: 3, number: 25, symbol: 'Mn', name: 'Manganese', mass: '54.94', category: 'transition' },
    { x: 7, y: 3, number: 26, symbol: 'Fe', name: 'Iron', mass: '55.85', category: 'transition' },
    { x: 8, y: 3, number: 27, symbol: 'Co', name: 'Cobalt', mass: '58.93', category: 'transition' },
    { x: 9, y: 3, number: 28, symbol: 'Ni', name: 'Nickel', mass: '58.69', category: 'transition' },
    { x: 10, y: 3, number: 29, symbol: 'Cu', name: 'Copper', mass: '63.55', category: 'transition' },
    { x: 11, y: 3, number: 30, symbol: 'Zn', name: 'Zinc', mass: '65.39', category: 'transition' },
    { x: 12, y: 3, number: 31, symbol: 'Ga', name: 'Gallium', mass: '69.72', category: 'post-transition' },
    { x: 13, y: 3, number: 32, symbol: 'Ge', name: 'Germanium', mass: '72.64', category: 'metalloid' },
    { x: 14, y: 3, number: 33, symbol: 'As', name: 'Arsenic', mass: '74.92', category: 'metalloid' },
    { x: 15, y: 3, number: 34, symbol: 'Se', name: 'Selenium', mass: '78.96', category: 'nonmetal' },
    { x: 16, y: 3, number: 35, symbol: 'Br', name: 'Bromine', mass: '79.90', category: 'halogen' },
    { x: 17, y: 3, number: 36, symbol: 'Kr', name: 'Krypton', mass: '83.80', category: 'noble-gas' },
    // Row 5
    { x: 0, y: 4, number: 37, symbol: 'Rb', name: 'Rubidium', mass: '85.47', category: 'alkali-metal' },
    { x: 1, y: 4, number: 38, symbol: 'Sr', name: 'Strontium', mass: '87.62', category: 'alkaline-earth' },
    { x: 2, y: 4, number: 39, symbol: 'Y', name: 'Yttrium', mass: '88.91', category: 'transition' },
    { x: 3, y: 4, number: 40, symbol: 'Zr', name: 'Zirconium', mass: '91.22', category: 'transition' },
    { x: 4, y: 4, number: 41, symbol: 'Nb', name: 'Niobium', mass: '92.91', category: 'transition' },
    { x: 5, y: 4, number: 42, symbol: 'Mo', name: 'Molybdenum', mass: '95.94', category: 'transition' },
    { x: 6, y: 4, number: 43, symbol: 'Tc', name: 'Technetium', mass: '(98)', category: 'transition' },
    { x: 7, y: 4, number: 44, symbol: 'Ru', name: 'Ruthenium', mass: '101.1', category: 'transition' },
    { x: 8, y: 4, number: 45, symbol: 'Rh', name: 'Rhodium', mass: '102.9', category: 'transition' },
    { x: 9, y: 4, number: 46, symbol: 'Pd', name: 'Palladium', mass: '106.4', category: 'transition' },
    { x: 10, y: 4, number: 47, symbol: 'Ag', name: 'Silver', mass: '107.9', category: 'transition' },
    { x: 11, y: 4, number: 48, symbol: 'Cd', name: 'Cadmium', mass: '112.4', category: 'transition' },
    { x: 12, y: 4, number: 49, symbol: 'In', name: 'Indium', mass: '114.8', category: 'post-transition' },
    { x: 13, y: 4, number: 50, symbol: 'Sn', name: 'Tin', mass: '118.7', category: 'post-transition' },
    { x: 14, y: 4, number: 51, symbol: 'Sb', name: 'Antimony', mass: '121.8', category: 'metalloid' },
    { x: 15, y: 4, number: 52, symbol: 'Te', name: 'Tellurium', mass: '127.6', category: 'metalloid' },
    { x: 16, y: 4, number: 53, symbol: 'I', name: 'Iodine', mass: '126.9', category: 'halogen' },
    { x: 17, y: 4, number: 54, symbol: 'Xe', name: 'Xenon', mass: '131.3', category: 'noble-gas' },
    // Row 6
    { x: 0, y: 5, number: 55, symbol: 'Cs', name: 'Cesium', mass: '132.9', category: 'alkali-metal' },
    { x: 1, y: 5, number: 56, symbol: 'Ba', name: 'Barium', mass: '137.3', category: 'alkaline-earth' },
    { x: 2, y: 5, number: 57, symbol: 'La-Lu', name: 'Lanthanides', mass: '138-175', category: 'lanthanide' },
    { x: 3, y: 5, number: 72, symbol: 'Hf', name: 'Hafnium', mass: '178.5', category: 'transition' },
    { x: 4, y: 5, number: 73, symbol: 'Ta', name: 'Tantalum', mass: '180.9', category: 'transition' },
    { x: 5, y: 5, number: 74, symbol: 'W', name: 'Tungsten', mass: '183.8', category: 'transition' },
    { x: 6, y: 5, number: 75, symbol: 'Re', name: 'Rhenium', mass: '186.2', category: 'transition' },
    { x: 7, y: 5, number: 76, symbol: 'Os', name: 'Osmium', mass: '190.2', category: 'transition' },
    { x: 8, y: 5, number: 77, symbol: 'Ir', name: 'Iridium', mass: '192.2', category: 'transition' },
    { x: 9, y: 5, number: 78, symbol: 'Pt', name: 'Platinum', mass: '195.1', category: 'transition' },
    { x: 10, y: 5, number: 79, symbol: 'Au', name: 'Gold', mass: '197.0', category: 'transition' },
    { x: 11, y: 5, number: 80, symbol: 'Hg', name: 'Mercury', mass: '200.6', category: 'transition' },
    { x: 12, y: 5, number: 81, symbol: 'Tl', name: 'Thallium', mass: '204.4', category: 'post-transition' },
    { x: 13, y: 5, number: 82, symbol: 'Pb', name: 'Lead', mass: '207.2', category: 'post-transition' },
    { x: 14, y: 5, number: 83, symbol: 'Bi', name: 'Bismuth', mass: '209.0', category: 'post-transition' },
    { x: 15, y: 5, number: 84, symbol: 'Po', name: 'Polonium', mass: '(209)', category: 'metalloid' },
    { x: 16, y: 5, number: 85, symbol: 'At', name: 'Astatine', mass: '(210)', category: 'halogen' },
    { x: 17, y: 5, number: 86, symbol: 'Rn', name: 'Radon', mass: '(222)', category: 'noble-gas' },
    // Row 7
    { x: 0, y: 6, number: 87, symbol: 'Fr', name: 'Francium', mass: '(223)', category: 'alkali-metal' },
    { x: 1, y: 6, number: 88, symbol: 'Ra', name: 'Radium', mass: '(226)', category: 'alkaline-earth' },
    { x: 2, y: 6, number: 89, symbol: 'Ac-Lr', name: 'Actinides', mass: '227-262', category: 'actinide' },
    { x: 3, y: 6, number: 104, symbol: 'Rf', name: 'Rutherfordium', mass: '(267)', category: 'transition' },
    { x: 4, y: 6, number: 105, symbol: 'Db', name: 'Dubnium', mass: '(268)', category: 'transition' },
    { x: 5, y: 6, number: 106, symbol: 'Sg', name: 'Seaborgium', mass: '(269)', category: 'transition' },
    { x: 6, y: 6, number: 107, symbol: 'Bh', name: 'Bohrium', mass: '(270)', category: 'transition' },
    { x: 7, y: 6, number: 108, symbol: 'Hs', name: 'Hassium', mass: '(269)', category: 'transition' },
    { x: 8, y: 6, number: 109, symbol: 'Mt', name: 'Meitnerium', mass: '(278)', category: 'transition' },
    { x: 9, y: 6, number: 110, symbol: 'Ds', name: 'Darmstadtium', mass: '(281)', category: 'transition' },
    { x: 10, y: 6, number: 111, symbol: 'Rg', name: 'Roentgenium', mass: '(282)', category: 'transition' },
    { x: 11, y: 6, number: 112, symbol: 'Cn', name: 'Copernicium', mass: '(285)', category: 'transition' },
    { x: 12, y: 6, number: 113, symbol: 'Nh', name: 'Nihonium', mass: '(286)', category: 'post-transition' },
    { x: 13, y: 6, number: 114, symbol: 'Fl', name: 'Flerovium', mass: '(289)', category: 'post-transition' },
    { x: 14, y: 6, number: 115, symbol: 'Mc', name: 'Moscovium', mass: '(290)', category: 'post-transition' },
    { x: 15, y: 6, number: 116, symbol: 'Lv', name: 'Livermorium', mass: '(293)', category: 'post-transition' },
    { x: 16, y: 6, number: 117, symbol: 'Ts', name: 'Tennessine', mass: '(294)', category: 'halogen' },
    { x: 17, y: 6, number: 118, symbol: 'Og', name: 'Oganesson', mass: '(294)', category: 'noble-gas' },

    // Lanthanides (y=8, offset below the table)
    { x: 2, y: 8, number: 57, symbol: 'La', name: 'Lanthanum', mass: '138.9', category: 'lanthanide' },
    { x: 3, y: 8, number: 58, symbol: 'Ce', name: 'Cerium', mass: '140.1', category: 'lanthanide' },
    { x: 4, y: 8, number: 59, symbol: 'Pr', name: 'Praseodymium', mass: '140.9', category: 'lanthanide' },
    { x: 5, y: 8, number: 60, symbol: 'Nd', name: 'Neodymium', mass: '144.2', category: 'lanthanide' },
    { x: 6, y: 8, number: 61, symbol: 'Pm', name: 'Promethium', mass: '(145)', category: 'lanthanide' },
    { x: 7, y: 8, number: 62, symbol: 'Sm', name: 'Samarium', mass: '150.4', category: 'lanthanide' },
    { x: 8, y: 8, number: 63, symbol: 'Eu', name: 'Europium', mass: '152.0', category: 'lanthanide' },
    { x: 9, y: 8, number: 64, symbol: 'Gd', name: 'Gadolinium', mass: '157.3', category: 'lanthanide' },
    { x: 10, y: 8, number: 65, symbol: 'Tb', name: 'Terbium', mass: '158.9', category: 'lanthanide' },
    { x: 11, y: 8, number: 66, symbol: 'Dy', name: 'Dysprosium', mass: '162.5', category: 'lanthanide' },
    { x: 12, y: 8, number: 67, symbol: 'Ho', name: 'Holmium', mass: '164.9', category: 'lanthanide' },
    { x: 13, y: 8, number: 68, symbol: 'Er', name: 'Erbium', mass: '167.3', category: 'lanthanide' },
    { x: 14, y: 8, number: 69, symbol: 'Tm', name: 'Thulium', mass: '168.9', category: 'lanthanide' },
    { x: 15, y: 8, number: 70, symbol: 'Yb', name: 'Ytterbium', mass: '173.0', category: 'lanthanide' },
    { x: 16, y: 8, number: 71, symbol: 'Lu', name: 'Lutetium', mass: '175.0', category: 'lanthanide' },

    // Actinides (y=9, offset below the table)
    { x: 2, y: 9, number: 89, symbol: 'Ac', name: 'Actinium', mass: '(227)', category: 'actinide' },
    { x: 3, y: 9, number: 90, symbol: 'Th', name: 'Thorium', mass: '232.0', category: 'actinide' },
    { x: 4, y: 9, number: 91, symbol: 'Pa', name: 'Protactinium', mass: '231.0', category: 'actinide' },
    { x: 5, y: 9, number: 92, symbol: 'U', name: 'Uranium', mass: '238.0', category: 'actinide' },
    { x: 6, y: 9, number: 93, symbol: 'Np', name: 'Neptunium', mass: '(237)', category: 'actinide' },
    { x: 7, y: 9, number: 94, symbol: 'Pu', name: 'Plutonium', mass: '(244)', category: 'actinide' },
    { x: 8, y: 9, number: 95, symbol: 'Am', name: 'Americium', mass: '(243)', category: 'actinide' },
    { x: 9, y: 9, number: 96, symbol: 'Cm', name: 'Curium', mass: '(247)', category: 'actinide' },
    { x: 10, y: 9, number: 97, symbol: 'Bk', name: 'Berkelium', mass: '(247)', category: 'actinide' },
    { x: 11, y: 9, number: 98, symbol: 'Cf', name: 'Californium', mass: '(251)', category: 'actinide' },
    { x: 12, y: 9, number: 99, symbol: 'Es', name: 'Einsteinium', mass: '(252)', category: 'actinide' },
    { x: 13, y: 9, number: 100, symbol: 'Fm', name: 'Fermium', mass: '(257)', category: 'actinide' },
    { x: 14, y: 9, number: 101, symbol: 'Md', name: 'Mendelevium', mass: '(258)', category: 'actinide' },
    { x: 15, y: 9, number: 102, symbol: 'No', name: 'Nobelium', mass: '(259)', category: 'actinide' },
    { x: 16, y: 9, number: 103, symbol: 'Lr', name: 'Lawrencium', mass: '(262)', category: 'actinide' },
];

export const categoryColors: Record<string, string> = {
    'alkali-metal': '#ff6b6b',
    'alkaline-earth': '#ffa94d',
    'transition': '#ffd43b',
    'post-transition': '#69db7c',
    'metalloid': '#38d9a9',
    'nonmetal': '#4dabf7',
    'halogen': '#748ffc',
    'noble-gas': '#da77f2',
    'lanthanide': '#f783ac',
    'actinide': '#e599f7',
};
